# VCSA 접속 정보 (VMware API 통신용)
vcenter_hostname: 10.10.10.3
vcenter_username: administrator@vsphere.local  # 실제 VCSA 관리 계정으로 변경 필요
vcenter_password: "VMware1!"         # 실제 VCSA 비밀번호로 변경 필요
vcenter_datacenter: Datacenter00
vcenter_cluster: Cluster-00            # 클러스터 이름으로 변경 필요

# Datastore 할당 (VMware VM 생성 시 사용)
vyos_datastore: datastore1
linux_datastore: datastore2

# VM 템플릿 이름 
vyos_template_name: vyos-template
linux_template_name: ro9-vm-template

# DVS Port Group 이름 (Playbook의 nics 변수에 사용)
pg_external: DPG-manage                        # VyOS Outside NIC 연결용
pg_internal: DPG-manage

# --- VyOS Router VM 설정 (VM Provisioning & Network Config Role 사용) ---
vyos_vm_name: vyos
vyos_os_user: vyos                              # VyOS VM에 설정된 SSH 접속 사용자
vyos_ssh_pass: "vyos"         # VyOS VM SSH 비밀번호
vyos_eth0_ip: 10.10.10.18/8                     # Outside NIC IP
vyos_eth1_ip: 172.16.1.100/16                   # Inside NIC IP
vyos_default_gateway: 10.0.0.1                  # Default Route Next-Hop

# ---linux VM 설정 (VM Provisioning & Nginx Role 사용) ---
linux_vm_name: linux
linux_os_user: root                  # Nginx VM에 설정된 SSH 접속 사용자
linux_ssh_pass: "VMware1!"    # Nginx VM SSH 비밀번호
linux_ip: 172.16.3.100/16                       # Nginx VM 최종 내부 IP
linux_gateway: 172.16.1.100                     # VyOS Inside IP (Nginx VM의 게이트웨이)



