---
# vars file for roles/nginx_deployment
nginx_package_name: nginx   #설치할 패키지 이름
nginx_service_name: nginx   # 서비스 관리 이름

# 설정 배포 관련 변수
nginx_conf_path: /etc/nginx/conf.d/default.conf
nginx_listen_port: 80
nginx_server_name: _
nginx_root_path: /usr/share/nginx/html
nginx_index_file: index.html
